#!/bin/sh
cd $(dirname $0)
LOG=./logs
mkdir -p $LOG
export SWT_GTK3=1
export SWT_WEBKIT2=1
/home/eclipse/sts-4.5.0.RELEASE/SpringToolSuite4 -data .. \
 >$LOG/eclipse-sts.log 2>$LOG/eclipse-sts.err.log &
