#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT=$(pwd)
./stop
mkdir -p logs
rm -f $ROOT/logs/run-*.log
SUSPEND="n"
ARGS=""
while (( "$#" )); do
	case $1 in
		suspend)
			SUSPEND="y"
			;;
		init)
			ARGS="init"
			;;
		*)
			echo "Unrecognized argument"
			exit 1
			;;
	esac
	shift
done
JVM_ARGS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=$SUSPEND,address=8000"
# JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
$JAVA_HOME/bin/java $JVM_ARGS -jar $(find target -name "*.jar") $ARGS\
 --server.port=9080\
 --spring.datasource.url=$DB_URL\
 --spring.datasource.username=$DB_USERNAME\
 --spring.datasource.password=$DB_PASSWORD\
  > $ROOT/logs/run-timesheet.log 2> $ROOT/logs/run-timesheet.err.log &
echo "$!" > $ROOT/logs/run-timesheet.pid
echo "running"